import React from 'react';
import { Link } from 'react-router';
import LegalPage from './LegalPage';
import { openCookieSettings } from '../lib/consent';

export default function Privacy() {
  return <LegalPage title="Privacy Policy" subtitle="Your information, the services we use, and your choices" updatedAt="October 4, 2026">
    <section className="legal-section"><h2>Who is responsible</h2>
      <p>Euclidean Software LLC operates PolyPDF and is responsible for the personal information described here. Contact <a href="mailto:support@polypdf.com?subject=Privacy%20request">support@polypdf.com</a> with a privacy question or request. This policy covers polypdf.com, direct purchases, licensing, support, and the desktop app. An employer or organisation operating a collaboration host is responsible for its own handling of shared project data.</p>
    </section>
    <section className="legal-section"><h2>Information we receive and why</h2><ul className="section-content">
      <li><strong>Website access:</strong> our host receives IP addresses, browser information, requested URLs and request times to deliver pages and downloads, keep services secure and diagnose failures. Avoid putting personal or confidential information into URLs.</li>
      <li><strong>Purchases and licensing:</strong> you and Stripe provide checkout email, billing or tax information where applicable, payment status, receipts and order identifiers. We use these to fulfil orders, deliver license keys, provide account access, process refunds and keep required financial records. Stripe handles payment credentials; the website does not collect your full card details.</li>
      <li><strong>Activation and updates:</strong> the app contacts licensing and update services with information such as app version, license status, activation timestamps and a random device identifier or its derived hash. These checks manage activation limits, prevent abuse and provide updates. They are separate from optional diagnostics.</li>
      <li><strong>Support and feature requests:</strong> we receive your email, correspondence and any files you choose to send. We use them to answer your request and investigate the issue. Please start with a description and avoid sending full license keys, confidential drawings or other people's personal information.</li>
      <li><strong>Optional website measurement:</strong> only with your choice, Google Analytics measures visits and interactions and Google Ads measures advertising results. Verified purchase events include an order identifier, value, currency and product, without your email, license key, PDF names or PDF content. Campaign source and UTM codes are stored only with advertising-measurement consent. We do not enable advertising personalization or Google signals in the website tag.</li>
      <li><strong>Optional desktop diagnostics:</strong> sharing is off by default and controlled in app settings. Reports can include app and operating-system information, a pseudonymous device identifier, redacted errors and fixed first-use milestones. Redaction aims to remove paths and filenames; do not include sensitive information in reports or support messages.</li>
      <li><strong>Optional desktop usage analytics:</strong> a separate, off-by-default choice lets you share fixed command and workflow signals so we can improve the product. Allowing error diagnostics does not enable usage sharing. The details and withdrawal choices are described below.</li>
    </ul><p>Information is received from you, your browser or app, and the payment, email and infrastructure providers involved in the service you request. Purchase and activation information is needed to provide a paid license; declining optional tracking does not prevent downloads, purchases or account use.</p></section>
    <section className="legal-section"><h2>Your documents and connected features</h2>
      <p>Core PDF viewing, measurement, markup and editing run locally. The app can keep recovery snapshots, save backups, preferences and recent-file records on your computer. These can contain document data and depend on your computer's access controls and backups; uninstalling the app may leave its support files behind.</p>
      <p>Documents may leave your device when you choose to share, export or use a connected workflow. Collaboration uses a customer-managed host and file share. PDF Maps may send map-area or search requests to the chosen map service. Optional timestamping sends a document digest to a timestamp provider. Email, storage, plugins and other services you choose have their own data practices. Review your organisation's policies before using them with confidential work.</p>
    </section>
    <section className="legal-section"><h2>Optional desktop usage analytics</h2>
      <p>When you explicitly enable usage sharing in app settings, the app sends PolyPDF a fixed set of product events, such as session starts, command invocations and results, committed markup types, and completed workflow signals. Reports include app version and build, operating-system family, event times, a coarse duration bucket where relevant, and a fixed source or outcome code. They help us understand useful features, failures and return activity. The app remains usable with sharing off, and automated test launches do not report usage.</p>
      <p>Usage reports use random installation, session and event identifiers generated independently of your license, account and hardware. They let us recognise repeated activity from an opted-in installation, so they are pseudonymous rather than a claim that activity cannot be linked. We do not join these identifiers to licensing, Teams, checkout or activation records. Reports go to PolyPDF's hosted service, not to website advertising tags.</p>
      <p>The usage endpoint does not collect PDF content, text or images, file names or paths, document or project identifiers, annotation text, form values, search terms, measurement values or coordinates, email addresses, account IDs, license keys, hardware fingerprints or arbitrary plugin names. Only predefined product commands and fixed categories are accepted. Workflow categories are inferred from completed actions using context that stays in memory on your device; no document reference is uploaded.</p>
      <p>You may optionally select a purpose such as takeoff, drawing review or signing in a separate question. Answering is not required for usage sharing or ordinary app use. The owner report labels this declared purpose separately from inferred workflows, and uses your latest answer. Clearing the answer or choosing “Prefer not to answer” removes the earlier answer from current purpose totals.</p>
      <p>You can turn usage sharing off in Settings at any time. This stops future uploads, aborts an in-flight upload where possible, clears the unsent local usage queue and discards the random usage identity. Re-enabling creates a new identity. The local queue is bounded and expires after seven days. A report already received cannot be recalled by turning sharing off; accepted events expire after 90 days. Backups follow our service backup controls and may contain earlier snapshots.</p>
      <p>Access to received usage is restricted to PolyPDF operators and the authenticated owner dashboard. The dashboard exposes aggregate counts, not raw installation or session IDs. Active-installation and return figures cover only reported, opted-in activity; they are not counts of people, all customers or installation-date retention. Operational web-server access logs are separate and can include IP addresses as described above.</p>
    </section>
    <section className="legal-section"><h2>Legal bases where UK or European data protection law applies</h2><ul className="section-content">
      <li><strong>Contract:</strong> processing necessary to take the steps you request before a purchase, fulfil it, provide licensing and account access, and deliver related support.</li>
      <li><strong>Legitimate interests:</strong> securing and maintaining our services, preventing fraud or abuse, and responding to enquiries, subject to your rights and interests.</li>
      <li><strong>Legal obligations:</strong> tax and accounting records, legally required disclosures and applicable consumer rights.</li>
      <li><strong>Consent:</strong> optional website analytics, advertising measurement, optional desktop diagnostics and the separate optional desktop usage analytics. Consent can be withdrawn for future collection without affecting processing that was lawful before withdrawal.</li>
    </ul></section>
    <section className="legal-section"><h2>Providers and international processing</h2>
      <p>Providers receive information needed for their role. They include <a href="https://stripe.com/privacy">Stripe</a> for payments, fraud prevention and receipts; <a href="https://resend.com/legal/privacy-policy">Resend</a> for transactional email; <a href="https://www.digitalocean.com/legal/privacy-policy">DigitalOcean</a> for hosting; and, when enabled, <a href="https://policies.google.com/privacy">Google</a> for website and advertising measurement. Support email and update delivery also involve email and infrastructure providers. Payment providers may act independently for their own fraud-prevention and legal obligations.</p>
      <p>These providers may process information in the United States and other countries, whose laws may differ from your own. Their published policies describe their processing locations and transfer arrangements. Contact us to request details of the providers and transfer safeguards relevant to your information. We may also disclose information when required by law or necessary to establish or defend legal claims.</p>
    </section>
    <section className="legal-section"><h2>Retention</h2><ul className="section-content">
      <li>License and activation records are retained while needed to service the perpetual license, manage activations, resolve disputes and prevent fraud. Financial and transaction records are kept as required by applicable tax and accounting law.</li>
      <li>PolyPDF-hosted diagnostic errors, opt-in activation milestones and opt-in usage events expire after 90 days. Expired account magic links and sessions are removed automatically. Sign-in links expire after one hour; an account session lasts up to 30 days or until sign-out.</li>
      <li>Cookie choices are remembered for 180 days. Consented campaign codes and local purchase-deduplication records have a 30-day validity period. Expired local records are removed when the site next checks them; clearing your browser's site data removes them sooner.</li>
      <li>Support correspondence is kept as needed to resolve and follow up on your request, maintain the relevant service history and address legal claims. Operational logs and provider records follow their service and security retention schedules. Contact us about a particular record or a deletion request.</li>
    </ul><p>The <Link to="/cookies/">Cookie Policy</Link> describes browser storage separately. Revoking tracking does not automatically erase information already received by providers; contact us for a data-rights request.</p></section>
    <section className="legal-section"><h2>Your rights and privacy choices</h2>
      <p>Depending on your location and the law that applies, you may request access, a copy, correction, deletion or portability of your personal information, restriction of processing, or object to processing based on legitimate interests. You can withdraw optional consent. We may need proportionate verification before responding and may retain information where a legal obligation or another lawful exception applies. We explain a refusal and any available appeal process.</p>
      <p>Email <a href="mailto:support@polypdf.com?subject=Privacy%20request">support@polypdf.com</a> with your request and the email used for the relevant interaction. Do not send a password, full license key or identity document in the first message. An authorised agent may contact us on your behalf; we may verify their authority. We respond within applicable legal time limits and do not deny access to ordinary website features because you exercise a privacy right.</p>
      <p>We do not sell personal information for money. Advertising disclosures can nevertheless count as a “sale” or “sharing” under some privacy laws. Our advertising measurement is off until you allow it. Use <button type="button" className="cookie-settings-button" onClick={openCookieSettings}>Cookie settings / Do not sell or share</button> to refuse or withdraw it. This site honours Global Privacy Control and Do Not Track by keeping all optional website tracking off in that browser. Choices apply to this browser; make the choice on each browser you use.</p>
      <p>You may complain to your local data protection authority. UK visitors can contact the <a href="https://ico.org.uk/make-a-complaint/">Information Commissioner's Office</a>; EEA visitors can contact their national supervisory authority. You do not have to contact us first.</p>
    </section>
    <section className="legal-section"><h2>Children and automated decisions</h2>
      <p>PolyPDF is intended for professional and general desktop document work, not directed at children under 13. We do not knowingly collect personal information from children under 13. Contact us if you believe a child has provided it. We use automated payment and activation checks to enforce license and security rules; contact support if a check incorrectly blocks your purchase or license.</p>
    </section>
    <section className="legal-section"><h2>Changes to this notice</h2>
      <p>We update the date when this notice changes. A new optional tracking purpose requires a new choice before it is enabled. Material changes will be brought to your attention as required by applicable law.</p>
    </section>
  </LegalPage>;
}
