import React, { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { ArrowRight, Check, Printer } from '@phosphor-icons/react';
import logo from '../assets/polypdf_icon-96.png';
import { ManagerDownload } from './TeamsJourney';
import './TeamsGuide.css';

const chapters = [
  ['overview', 'Start here'], ['purchase', 'Purchase seats'], ['prepare', 'Prepare your server'],
  ['install', 'Install & configure'], ['connect', 'Connect your purchase'], ['people', 'Assign people'],
  ['employees', 'Employee sign-in'], ['collaboration', 'Share PDFs together'], ['troubleshooting', 'Resolve an issue'], ['maintenance', 'Maintain your service'],
];
export const employeeChecklist = 'Getting started with PolyPDF\n1. Install the PolyPDF version supplied by your IT administrator.\n2. Open PolyPDF licensing, choose Open company profile, and select the polypdf-company.json file supplied by IT. You can also enter the company HTTPS address.\n3. Choose Sign in with your company. For Microsoft mode, complete company sign-in and confirm your computer. For local mode, enter the private invitation from IT and ask IT to confirm the matching code and approve your computer. Return to PolyPDF.\nYour administrator must assign your seat. Connect to the company network or VPN if needed. Contact your IT administrator if sign-in or access fails.';

function Chapter({ id, number, title, children }) {
  return <section id={id} className="team-guide-chapter" aria-labelledby={`${id}-title`}><div className="team-guide-section-label">{number}</div><h2 id={`${id}-title`}>{title}</h2>{children}</section>;
}
function Outcome({ children }) {
  return <p className="team-guide-outcome"><Check size={19} weight="bold" aria-hidden="true" /><span><strong>You’re ready when</strong> {children}</span></p>;
}
function CopyInstructions() {
  const [message, setMessage] = useState('');
  const copy = async () => {
    try { await navigator.clipboard.writeText(employeeChecklist); setMessage('Employee checklist copied. Attach your company connection file before sending.'); }
    catch { setMessage('Copy is unavailable. Select the checklist below and copy it manually.'); }
  };
  return <div className="team-guide-share"><button type="button" onClick={copy}>Copy employee checklist</button><p role="status" aria-live="polite">{message}</p><details><summary>Read or copy the checklist</summary><pre>{employeeChecklist}</pre></details></div>;
}
export default function TeamsGuide() {
  useEffect(() => {
    let closed = [];
    const beforePrint = () => { closed = Array.from(document.querySelectorAll('.team-guide details:not([open])')); closed.forEach(item => { item.open = true; }); };
    const afterPrint = () => { closed.forEach(item => { item.open = false; }); closed = []; };
    window.addEventListener('beforeprint', beforePrint);
    window.addEventListener('afterprint', afterPrint);
    return () => { window.removeEventListener('beforeprint', beforePrint); window.removeEventListener('afterprint', afterPrint); afterPrint(); };
  }, []);
  return <main className="team-guide">
    <div className="team-guide-top"><Link to="/" className="team-guide-brand"><img src={logo} alt="" width="36" height="36" /><span>PolyPDF <small>Teams guide</small></span></Link><Link to="/teams">Teams account <ArrowRight size={16} aria-hidden="true" /></Link></div>
    <header className="team-guide-hero"><div><p className="team-guide-eyebrow">SETUP & ADMINISTRATION</p><h1>Your team, ready to work.</h1><p>Set up your company’s license service once. Assign your people. Connect them through Microsoft sign-in or locally approved invitations.</p><div className="team-guide-actions"><a href="#prepare" className="team-guide-primary">Set up for your company <ArrowRight size={18} aria-hidden="true" /></a><a href="#employees">I’m an employee <ArrowRight size={18} aria-hidden="true" /></a></div></div><aside className="team-guide-at-a-glance" aria-label="Setup responsibilities"><p className="team-guide-eyebrow">WHO DOES WHAT</p><dl><div><dt>Billing owner</dt><dd>Purchase seats and connect the manager.</dd></div><div><dt>IT administrator</dt><dd>Configure the server and assign people.</dd></div><div><dt>Employee</dt><dd>Install PolyPDF and sign in.</dd></div></dl></aside></header>
    <div className="team-guide-layout"><nav className="team-guide-contents" aria-label="Guide contents"><p>IN THIS GUIDE</p><ol>{chapters.map(([id, label]) => <li key={id}><a href={`#${id}`}>{label}</a></li>)}</ol><button type="button" onClick={() => window.print()}><Printer size={17} aria-hidden="true" /> Print guide</button><Link to="/support">Get help</Link></nav><article className="team-guide-body">
      <Chapter id="overview" number="OVERVIEW" title="A desktop console for IT. A simple sign-in for everyone.">
        <p>License Manager is a Windows desktop app backed by a service on your company server. Open it from the Start menu to manage people, seats and computers. Closing the window leaves licensing running.</p>
        <ol className="team-guide-flow" aria-label="Company setup sequence">{['Prepare server', 'Install manager', 'Connect purchase', 'Assign people', 'Share instructions'].map((label, index) => <li key={label}><span>{String(index + 1).padStart(2, '0')}</span>{label}</li>)}</ol>
        <p className="team-guide-note">This guide covers License Manager 1.0.1 and PolyPDF 1.6.2. The License Manager belongs on the server; employees install PolyPDF on their own Mac or Windows computer.</p>
        <p>One Teams seat covers one named employee on one active computer. An administrator does not need a seat just to manage the company. Personal licenses remain separate and keep their existing rights.</p>
      </Chapter>
      <Chapter id="purchase" number="01 / BILLING OWNER" title="Choose your seats.">
        <ol><li>Open your <Link to="/teams">Teams account</Link>. Choose at least <strong>3 users</strong> with the slider or exact quantity field.</li><li>Verify the billing-owner email, enter your company name, and review the quote and Teams terms.</li><li>Complete payment. Return to your account and refresh purchases until the order is marked <strong>Paid</strong> and the purchased capacity is available.</li></ol>
        <div className="team-guide-table"><table><caption>One-time prices in USD, before tax</caption><thead><tr><th scope="col">Resulting paid seats</th><th scope="col">Price per new seat</th></tr></thead><tbody><tr><td>3–24</td><td>$24.98</td></tr><tr><td>25–99</td><td>$22.48</td></tr><tr><td>100+</td><td>$19.98</td></tr></tbody></table></div>
        <p>100 seats cost <strong>$1,998 before tax</strong>. Add-on purchases also require at least 3 seats. Your resulting paid seat count determines the rate for newly purchased seats; earlier purchases are not repriced. Seats include perpetual PolyPDF 1.x use and all 1.x updates.</p>
        <p>If payment is pending, wait and refresh; do not pay again. A return-page visit does not activate seats. Use <strong>Orders and receipts → View receipt / invoice</strong> for paid orders.</p>
        <Outcome>your account shows the paid seat capacity. Employee assignments happen in your company’s manager.</Outcome>
      </Chapter>
      <Chapter id="prepare" number="02 / IT ADMINISTRATOR" title="Have these details ready.">
        <dl className="team-guide-requirements"><div><dt>Windows host</dt><dd>Windows Server 2022 or 2025, x64, with local administrator access for setup. The installer includes its runtime; no development tools are needed.</dd></div><div><dt>Company address</dt><dd>A DNS hostname that resolves to the server and is reachable from employee computers, including over your VPN when required.</dd></div><div><dt>Trusted HTTPS</dt><dd>A matching certificate with its full intermediate chain and private key, both in PEM format. The server and employee computers must trust the issuing authority.</dd></div><div><dt>Sign-in method</dt><dd>Choose Microsoft Entra or local invitations. Microsoft mode needs one workforce tenant, a dedicated single-tenant application, a client secret, and the initial administrator’s user object ID. Local mode uses Windows administrator approval on the server and needs no Entra registration.</dd></div><div><dt>Network access</dt><dd>Inbound HTTPS on port 7444 from authorized company computers. Outbound HTTPS to <code>www.polypdf.com</code> for purchased-capacity validation. Microsoft mode also needs access to Microsoft Entra.</dd></div></dl>
        <details className="team-guide-detail"><summary>Prepare the Microsoft app registration</summary><ol><li>In Microsoft Entra, open <strong>App registrations → New registration</strong>. Choose accounts in your organizational directory only.</li><li>Add a <strong>Web</strong> redirect URI using your company hostname: <code>https://licenses.yourcompany.com:7444/auth/callback</code>. Replace the example hostname with yours. The setup wizard shows the exact value to register.</li><li>Record the <strong>Directory (tenant) ID</strong> and <strong>Application (client) ID</strong>. Create a client secret and securely record its <strong>value</strong>, not its secret ID, and expiration date.</li><li>Find the initial administrator under your tenant’s users and copy that user’s <strong>Object ID</strong>. Do not use the application’s object ID or an email address.</li><li>Apply your organization’s access, consent and MFA policies. If application assignment is required, assign the administrator and intended employees. Directory assignment and PolyPDF seat assignment are separate.</li></ol><p>The manager handles browser sign-in; register the callback as Web even though employees use a desktop app. Do not enable implicit flows. Automatic group synchronization, SCIM and SAML are not supported.</p><a href="https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app" target="_blank" rel="noopener noreferrer">Microsoft’s app registration instructions</a></details>
        <Outcome>the hostname resolves, HTTPS can be trusted on every participating computer, and IT has chosen the sign-in method. Prepare Entra details only for Microsoft mode.</Outcome>
      </Chapter>
      <Chapter id="install" number="03 / IT ADMINISTRATOR" title="Install the console. Configure the server.">
        <div className="team-guide-download"><ManagerDownload /></div>
        <ol><li>Run the signed Windows License Manager installer. Verify the publisher is <strong>Euclidean Software, LLC</strong>. Complete installation.</li><li>Open <strong>Start → PolyPDF Teams → License Manager</strong>, then choose <strong>Set up this server</strong>. Approve the Windows administrator prompt for the installed setup helper.</li><li>In <strong>Company server</strong>, enter the hostname without <code>https://</code>, a port or a path. Select the certificate chain and matching private key.</li><li>In <strong>Sign-in method</strong>, choose <strong>Microsoft Entra ID</strong> or <strong>Local invitations and computer approval</strong>. This choice is fixed for the installation; existing managers keep their current method.</li><li>For Microsoft mode, in <strong>Microsoft details</strong>, enter the tenant ID, client ID, administrator user object ID and client secret.</li><li>In <strong>Review & install</strong>, check the HTTPS address. For Microsoft mode, copy the Entra Web redirect URI and check it matches your registration. Local mode needs no callback registration. Choose <strong>Install manager</strong>.</li><li>When the console is ready, choose <strong>Sign in with Microsoft</strong>. Complete sign-in in the system browser, compare its code with the console’s code, then choose <strong>Open desktop console</strong>. Return to License Manager. For local mode, choose <strong>Continue with Windows administrator</strong> on the server, approve Windows elevation, and confirm the matching code in the approval dialog.</li></ol>
        <p>You can cancel setup and start it again from the console. An already configured server is detected automatically, so an upgrade does not require re-entering company credentials.</p>
        <p className="team-guide-note">Microsoft mode uses the system browser for authentication and confirmation. Local administration uses Windows approval on the company server; local employees use their browser to request computer approval. Day-to-day administration stays in the desktop console. A company HTTPS address connects the console and employees to the background service.</p>
        <Outcome>the desktop console opens <strong>People & licenses</strong>. A new manager shows 0 purchased seats until you connect your purchase.</Outcome>
      </Chapter>
      <Chapter id="connect" number="04 / IT + BILLING OWNER" title="Connect your purchased seats.">
        <ol><li>In License Manager, open <strong>Service health</strong> and choose <strong>Copy public key</strong>.</li><li>The billing owner opens the correct company in the <Link to="/teams">Teams account</Link>, expands <strong>Connect an installed manager</strong>, and pastes that public key.</li><li>Choose <strong>Generate enrollment code</strong>. Copy the code and paste it into <strong>Enrollment code</strong> in the manager’s Service health screen.</li><li>Choose <strong>Enroll manager</strong>. Check that the purchased capacity appears in <strong>People & licenses</strong>.</li></ol>
        <p>Enrollment codes expire after ten minutes and work once. If a code expires, generate another for the same manager public key; the previous code stops working. Keep enrollment codes private.</p>
        <p>One manager can be active per company. Use <strong>Replace your license manager</strong> only when intentionally moving to another manager, and review the replacement confirmation.</p>
        <Outcome>the manager shows the correct purchased capacity and Service health reports validated authorization.</Outcome>
      </Chapter>
      <Chapter id="people" number="05 / IT ADMINISTRATOR" title="Assign people, then share the connection file.">
        <ol><li>Open <strong>People & licenses</strong>. For Microsoft mode, use the employee’s immutable Entra user object ID. For local mode, enter their name and a stable employee ID; the console can generate this ID for you. Choose <strong>Download CSV template</strong> for a larger team.</li><li>For Microsoft mode, populate <code>objectId</code>. For local mode, populate <code>employeeId</code> and <code>displayName</code>; reuse the same employee ID for later updates. Both modes accept optional <code>email</code> and <code>assign</code> (true or false); <code>displayName</code> is optional only in Microsoft mode. Review the import preview and correct invalid or duplicate rows before applying.</li><li>Choose <strong>Assign seat</strong> for each person who needs Pro access. In Microsoft mode, unassigned sign-ins appear as pending requests; an email domain never grants a license.</li><li>Choose <strong>Download company connection file</strong> and <strong>Copy employee instructions</strong>. Share the file and instructions through your normal company channel.</li></ol>
        <details className="team-guide-detail"><summary>Invite and approve employees in local mode</summary><ol><li>Assign the named employee a seat, then choose <strong>Create invitation</strong> beside their name. Copy the private invitation and send it directly through a known company channel.</li><li>The invitation expires after 24 hours and works once. Creating a new invitation cancels any earlier unused code. Invitations do not activate a computer or grant a seat.</li><li>The employee opens their company connection file in PolyPDF, chooses company sign-in, and enters the invitation in the browser. They contact IT with the matching code.</li><li>Open <strong>Devices</strong> and refresh. Under <strong>Computer requests</strong>, choose <strong>Review &amp; approve</strong>. Contact the named employee using a known channel, enter the matching code they confirm, and approve within the ten-minute request window.</li><li>If they already have a computer, explicitly confirm its replacement and review the old computer’s offline deadline. PolyPDF on the initiating computer completes activation automatically.</li></ol><p>If a request expires or is declined, create a new invitation and have the employee start again. A changed seat assignment invalidates outstanding requests. Local mode has no employee password reset: IT verifies the person and approves a new computer.</p></details>
        <p>The connection file contains only your manager’s HTTPS address and the connection format version. It contains no credentials or employee identities. Assignment and first-computer progress stay in the local manager.</p>
        <p>For staff changes, use <strong>Remove seat</strong> or <strong>Reassign</strong> in People & licenses and review the old computer’s remaining offline deadline. Entra directory changes do not automatically remove local assignments; IT must remove seats in the manager. Use <strong>Devices</strong> to review active computers and <strong>Activity</strong> to review the change.</p>
        <Outcome>each intended employee has a seat and receives the connection file, installation instructions and your IT contact.</Outcome>
      </Chapter>
      <Chapter id="employees" number="FOR EMPLOYEES" title="Three steps. No license key to copy.">
        <ol className="team-guide-employee-steps"><li><strong>Install PolyPDF.</strong><p>Use the Teams-compatible Mac or Windows release supplied by IT. Connect to your company network or VPN if your license service requires it.</p></li><li><strong>Open your company profile.</strong><p>In PolyPDF licensing, choose <strong>Open company profile</strong> and select IT’s <code>polypdf-company.json</code> file. You can also enter the company HTTPS address manually.</p></li><li><strong>Sign in with your company.</strong><p>Choose <strong>Sign in with your company</strong>. For Microsoft mode, complete sign-in and any MFA in your browser and confirm the computer. For local mode, enter IT’s private invitation in the browser, then contact IT to confirm the matching code and approve this computer. Keep PolyPDF open and return after approval.</p></li></ol>
        <p>Check the company-license status for your organization, assigned user, computer, connection and offline expiry. If no seat is assigned, ask your IT administrator to assign one, then retry. Keep any existing personal key; company sign-in is separate.</p>
        <CopyInstructions />
        <Outcome>PolyPDF shows active company access for you and this computer.</Outcome>
      </Chapter>
      <Chapter id="collaboration" number="OPTIONAL / IT + EMPLOYEES" title="Work together on your company’s PDFs.">
        <p>One Teams seat also covers company collaboration. Your firm runs the Collaboration Host and keeps its PDFs and collaboration history on its own server. Employees with a seat and an approved computer can open and mark up PDFs on the company share without another invitation or a separate collaboration role. An administrator needs a seat to work on PDFs too.</p>
        <ol><li>IT: install the signed <a href="/downloads/collaboration/PolyPDF-Collaboration-Host-Setup.exe">Collaboration Host for Windows Server</a> on a company server. It may share the License Manager’s server but keeps separate data and keys. During setup, choose the folder containing the company PDFs. Make the share available to employee computers over the company network or VPN. The installer’s First Owner invitation is for standalone hosts; do not distribute it for a Teams host.</li><li>IT: in <strong>License Manager → Collaboration</strong>, choose <strong>Create setup code</strong>. On the host server, run the Windows PowerShell pairing command shown in the console within ten minutes. The code works once. Compare the six-digit code shown by the host with the one in the manager, type the host’s code into the manager and choose <strong>Confirm pairing</strong>.</li><li>IT: choose <strong>Check connectivity</strong> in the manager. Confirm the host is reachable, the PDF share is writable and seat status has synchronized. If the host used standalone invitations before pairing, use <strong>Review device memberships</strong> to map each existing computer to its named employee; the manager will not guess from names or email addresses.</li><li>Employee: after company sign-in is active, open <strong>PolyPDF → Settings → Collaboration</strong> and choose <strong>Connect with company sign-in</strong> once. Open a PDF from the company share to work with colleagues.</li></ol>
        <p className="team-guide-note">A manager outage may interrupt live sharing even while an offline Pro license remains valid. PolyPDF keeps local changes safely queued until company collaboration access returns. If IT removes a seat or replaces a computer, the host stops that computer’s shared access; its offline Pro deadline does not extend collaboration access.</p>
        <Outcome>the manager shows a paired, reachable host and an employee can open a shared PDF with company sign-in.</Outcome>
      </Chapter>
      <Chapter id="troubleshooting" number="WHEN SOMETHING NEEDS ATTENTION" title="Get back to work.">
        <details className="team-guide-detail"><summary>Sign-in expired or was cancelled</summary><p>Return to the app and start sign-in again. Use the newly opened browser request and compare the current code. Old tabs and previous codes cannot complete the new request.</p></details>
        <details className="team-guide-detail"><summary>The server is unavailable</summary><p>Connect to the company network or VPN. Check the company address. IT should verify the Windows service is running, DNS resolves and port 7444 is reachable. In License Manager, choose <strong>Refresh</strong> once the service recovers. Valid cached employee access remains available until its displayed expiry.</p></details>
        <details className="team-guide-detail"><summary>Certificate or secure-connection error</summary><p>Ask IT to check the certificate’s hostname, expiration and full chain, and the computer’s clock and certificate trust. Do not bypass the warning. Retry after IT repairs the certificate or trust configuration.</p></details>
        <details className="team-guide-detail"><summary>Wrong Microsoft account, tenant or redirect URI</summary><p>Sign in with your company account in the configured tenant. IT should verify the tenant/client IDs and exact Web callback URI, including port and path. If Microsoft requests consent or denies application access, the Entra administrator must review company policy.</p></details>
        <details className="team-guide-detail"><summary>No seat or a computer replacement request</summary><p>IT should assign the correct named employee (Entra object ID or local employee ID) and confirm purchased capacity is available. For a new computer, explicitly confirm replacement during Microsoft sign-in, or have an administrator approve replacement under Devices in local mode. Each employee has one active computer; the previous computer loses online access at its next check, within five minutes. Its remaining offline access lasts only until the displayed deadline.</p></details>
        <details className="team-guide-detail"><summary>Enrollment code rejected or purchase still pending</summary><p>Confirm the order is Paid and you selected the correct company. Generate a fresh code for the public key currently shown in Service health. Use it within ten minutes. If payment is pending, refresh purchases rather than paying again. Contact support if the status does not resolve.</p></details>
        <details className="team-guide-detail"><summary>Collaboration pairing or shared PDFs are unavailable</summary><p>Create a fresh setup code if the old one expired or was used. Compare the verification codes on the host and manager before confirming; if they differ, cancel and start again. Check that the host is running, its PDF share is writable, and employee computers can reach the host over the company network or VPN. In License Manager → Collaboration, choose <strong>Check connectivity</strong> and review the result. Employees should confirm their company seat and approved computer, then retry <strong>Connect with company sign-in</strong> in PolyPDF’s Collaboration settings.</p></details>
        <details className="team-guide-detail"><summary>Client secret expired or administrator cannot sign in</summary><p>IT should renew the dedicated Entra application’s secret and use the local maintenance tool to rotate it. A Windows administrator can recover manager access for a valid Entra user object ID. See the maintenance steps below. Signing in does not bypass company MFA or access policies.</p></details>
        <p>Employees should contact their IT administrator first. For product help, <Link to="/support">contact PolyPDF support</Link> with the error’s support reference, app and manager versions, and the time it occurred. Do not include passwords, client secrets, enrollment codes or private keys.</p>
      </Chapter>
      <Chapter id="maintenance" number="ONGOING / IT ADMINISTRATOR" title="Keep the service ready.">
        <p>Use <strong>Service health</strong> to check authorization and <strong>Activity</strong> to review administrative changes. Closing the console does not stop the service. Keep the server available and renew certificates and Microsoft credentials before they expire.</p>
        <details className="team-guide-detail"><summary>Backup, upgrade and restore</summary><p>On the company server, open <strong>Service health → Back up now</strong>, approve the Windows administrator prompt, and choose a destination. The console creates a new protected backup folder containing the database, credentials, signing authority and HTTPS files. Keep a secure copy off the server after important changes and before upgrades. Service health shows the last backup time.</p><p>Run the signed newer installer to upgrade. Reopen the console and confirm the company, purchased capacity and service status. Uninstalling retains company data.</p><p>Choose <strong>Restore backup</strong> and select a complete backup folder for this server. Review the confirmation: newer assignments and settings will be replaced. The tool validates the backup, preserves current data in a protected recovery copy, briefly stops the service and clears administrator sessions and outstanding invitations. Sign in again and review assignments and authorization before employees reconnect. For a different manager or hostname, use the billing account’s manager replacement process.</p></details>
        <details className="team-guide-detail"><summary>Certificates, client secrets and administrator recovery</summary><p>These controls are available in <strong>Service health</strong> and on the console welcome screen, including when Microsoft sign-in or HTTPS is unavailable. Use the console on the company Windows server and approve the Windows administrator prompt.</p><ul><li><strong>Install renewed certificate</strong>: obtain a renewed certificate from your company or public issuer, then select its PEM chain and matching private key. The tool checks the hostname, trust and key, restarts the service, and restores the old certificate if the live HTTPS check fails. Employee computers must trust the issuer. This does not automatically request a certificate from an issuer.</li><li><strong>Renew Microsoft credential</strong>: securely enter the new client-secret value for the existing Entra application.</li><li><strong>Recover Microsoft administrator</strong>: supply the administrator’s Entra user object ID. They still complete company sign-in and MFA.</li></ul><p>In local mode, Windows administrators on the host control administration. No employee can make themselves an administrator. Keep access to a Windows administrator account and a protected backup. In Microsoft mode, the manager prevents removal of its last administrator.</p></details>
        <h3>Understand offline access</h3><p>The manager validates purchased capacity daily. Employee apps check on launch, reconnection and every five minutes while online. Offline access lasts no more than seven days and never outlives the company authorization.</p><p>Removing or reassigning a seat prevents the manager from issuing further access to the former holder immediately. Connected computers apply the change by their next check; offline computers retain only their existing entitlement until its displayed deadline. Replacement can therefore create a bounded period of offline overlap.</p><p>If access expires, documents and unsaved edits remain available to save or export. New Pro operations are blocked until access is restored.</p>
        <h3>Your firm controls employee access</h3><p>Employees use your firm’s Microsoft Entra accounts or locally approved invitations; they do not create PolyPDF accounts. The PolyPDF website account is for the billing owner to purchase seats and enroll the manager. Your administrator controls employee assignments and computers in the company-hosted manager.</p><p>Microsoft mode authenticates through Microsoft’s cloud. Local invitation mode keeps employee enrollment and computer approval entirely on your company server. Both modes still validate purchased capacity with PolyPDF daily and have bounded offline access; neither is an air-gapped license system.</p><h3>What stays with your company</h3><p>Employee identities, seat assignments, device details and administrative history stay on your company manager. Licensing collects no PDFs, filenames, paths, thumbnails or document activity. Microsoft handles authentication only when you choose Entra mode. PolyPDF receives organization/license identifiers, manager identity and authorization version to validate purchased capacity.</p>
      </Chapter>
      <div className="team-guide-end"><h2>Ready for your team.</h2><p>Keep this guide with your IT runbook. Share the employee section with everyone getting started.</p><Link to="/teams">Open Teams account <ArrowRight size={18} aria-hidden="true" /></Link><a href="#employees">Employee instructions</a></div>
    </article></div>
  </main>;
}
