import React from 'react';
import { Link } from 'react-router';
import './Teams.css';
import { ManagerDownload } from './TeamsJourney';
export default function TeamsSetup() {
  return <div className="teams-page"><article className="teams-wrap">
    <Link to="/teams" className="teams-brand">PolyPDF <span>Teams setup</span></Link>
    <header className="teams-hero"><p className="teams-kicker">Getting your team started</p><h1>IT connects it once.<br />Everyone else signs in.</h1><p>Employees need only PolyPDF, their company connection address, and their Microsoft account.</p></header><section className="teams-panel"><h2>For employees: three quick steps</h2><ol className="teams-setup-checklist"><li>Install the PolyPDF release supplied by your IT administrator on your Mac or Windows computer.</li><li>In PolyPDF licensing, choose <strong>Open company profile</strong> and select the connection file supplied by IT, or enter the company address. Then choose <strong>Sign in with your company</strong>.</li><li>Sign in with Microsoft, confirm your computer, and return to PolyPDF.</li></ol><p>Your administrator assigns your seat. You never need to copy a license key.</p></section><section className="teams-panel"><h2>For IT: before you begin</h2><ul className="teams-setup-checklist"><li>A Windows Server 2022 or 2025 host.</li><li>A company HTTPS hostname and trusted certificate.</li><li>Your Entra tenant, app registration, and initial administrator.</li></ul><ManagerDownload /></section>
    <details className="teams-panel"><summary>Step 1 · Prepare your server and Microsoft sign-in</summary><p>Use Windows Server 2022 or 2025 x64. Reserve an internal DNS hostname reachable by employees on your network or VPN. Obtain a matching HTTPS certificate and its private key in PEM format, with the full intermediate chain. Employees and the server must trust the issuing certificate authority.</p><p>Create a dedicated, single-tenant Microsoft Entra workforce application with a Web redirect URI of <code>https://your-hostname:7444/auth/callback</code>. Use authorization code sign-in; the manager uses PKCE, state and nonce. Do not enable implicit token flows. Supply your tenant ID, application client ID, and a client secret to setup. Apply your organization’s consent and Conditional Access policies, including MFA. Record the immutable Entra object ID of the initial administrator.</p><p>Allow employee access to HTTPS port 7444. Allow outbound HTTPS to Microsoft Entra sign-in endpoints and <code>www.polypdf.com</code>. An administrator role alone does not consume a purchased seat.</p></details>
    <details className="teams-panel"><summary>Steps 2–3 · Install the manager and connect your purchase</summary><p>Run the signed PolyPDF License Manager installer as a Windows administrator. Open <strong>Start → PolyPDF Teams → License Manager</strong> and choose <strong>Set up this server</strong>. The desktop console’s guided setup collects the hostname, certificate, Entra settings, and initial administrator object ID. It creates a dedicated restricted service identity and protects the configuration, database, credentials and keys under <code>C:\ProgramData\PolyPDF\LicenseManager</code>.</p><p>Choose <strong>Sign in with Microsoft</strong> in the desktop console. Confirm the matching code in your browser; the console opens automatically. Copy the manager public key from Service health. In your <Link to="/teams">Teams billing account</Link>, select the organization and generate an enrollment code for that key. Paste the code into the manager within ten minutes. Codes can be used once.</p><p>Only one manager may be active for an organization. Replacement requires explicit confirmation and rotates the company authority; earlier offline access can last until its existing expiry, at most seven days.</p></details>
    <details className="teams-panel"><summary>Steps 4–5 · Assign people and share employee instructions</summary><p>Download the CSV template from People & licenses. Import a CSV containing <code>objectId</code>. Optional columns are <code>displayName</code>, <code>email</code>, and <code>assign</code> (true or false). Preview before applying. Use immutable Entra object IDs, not email addresses, for assignments. Employees who sign in without a seat appear for administrator review; matching an email domain never grants access.</p><p>In the manager, select “Download company connection file” and “Copy employee instructions.” Share them with employees using your company’s usual channel. In PolyPDF, open licensing and choose “Sign in with your company.” Enter the manager’s HTTPS address, or select an IT-distributed JSON connection profile containing <code>{'{"protocol":1,"managerUrl":"https://your-hostname:7444"}'}</code>. Complete browser sign-in, confirm the named computer, and return to PolyPDF.</p><p>Each employee uses one active computer. To replace it, sign in on the new computer and explicitly confirm replacement in the browser. Previous online access is revoked immediately; the manager displays the maximum remaining offline deadline. Personal keys remain separate.</p></details>
    <details className="teams-panel"><summary>Maintenance and recovery</summary><p>Closing the desktop console leaves licensing running. The configured service starts automatically and recovers after an unexpected process exit. The Service health screen shows the last vendor validation and authorization expiry. The manager validates the purchased pool daily; desktop apps check on launch, reconnection and every five minutes while online. Employee leases never outlive the company authorization or seven days.</p><p>Use the installed <code>maintenance.ps1</code> tool from an administrator PowerShell session. <code>-Action Backup -BackupPath &lt;protected directory&gt;</code> creates a consistent database and credential backup. Store it securely: it contains signing authority and authentication credentials. <code>-Action Restore -BackupPath &lt;directory&gt;</code> stops the service and restores that backup. Keep installation binaries with the backup for rollback.</p><p><code>-Action RecoverAdmin -ObjectId &lt;Entra object ID&gt;</code> restores local administrative access. <code>-Action ReplaceCertificate -CertificatePath &lt;PEM&gt; -PrivateKeyPath &lt;PEM&gt;</code> replaces HTTPS material. <code>-Action RotateIdentitySecret</code> securely prompts for a replacement Entra client secret and restarts the service. Plan certificate and client-secret renewal before expiry. Uninstall retains company data; permanent purge requires an explicit confirmation.</p></details>
    <section className="teams-panel"><h2>Privacy and access during outages</h2><p>Employee identities, assigned seats, devices and administration history stay in your company’s manager. PolyPDF receives only organization/license identifiers, manager identity and authorization version for pool validation. No PDFs, filenames, file paths, thumbnails or document activity are collected by licensing.</p><p>Valid cached access survives temporary outages. At expiry, existing documents and unsaved edits remain available to save or export; new Pro operations are blocked until access is restored. Removing an employee’s local seat immediately prevents new access from being issued. Connected computers apply the change at their next check, within five minutes; disconnected computers retain access only until the displayed offline deadline. Automatic directory synchronization is outside this release.</p><Link to="/support">Contact PolyPDF support</Link></section>
  </article></div>;
}
