name: CI/CD Pipeline for polypdf-site

on:
  push:
    branches:
      - master  # Changed from main to master since that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Droplet to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Droplet
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            set -e
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            # Navigate to the polypdf-site directory
            cd /var/www/polypdf-site
            
            # Stash any local changes and pull latest code
            git stash
            git pull origin master

            # Install dependencies and build the React app
            npm install
            npm run build

            # For React apps, we typically serve the build folder with nginx or a static server
            # If using pm2 with serve:
            npm install -g serve
            
            # Check if the app is already running in pm2
            if pm2 describe polypdf-site > /dev/null; then
              pm2 reload polypdf-site
            else
              # Serve the build folder on port 3001 (or your preferred port)
              pm2 start serve --name "polypdf-site" -- -s build -l 3001
            fi

            # Save pm2 configuration
            pm2 save
            
            # Optional: If using nginx, restart it to pick up any config changes
            # sudo systemctl reload nginx
          EOF