name: CI/CD Pipeline for polypdf-site (Nginx)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Droplet to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Droplet
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            set -e
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            # Navigate to the polypdf-site directory
            cd /var/www/polypdf-site
            
            # Stash any local changes and pull latest code
            git stash
            git pull origin master

            # Install dependencies and build the React app
            npm install
            npm run build

            # Copy build files to nginx directory (adjust path as needed)
            sudo rm -rf /var/www/html/polypdf-site/*
            sudo cp -r build/* /var/www/html/polypdf-site/

            # Ensure proper permissions
            sudo chown -R www-data:www-data /var/www/html/polypdf-site
            
            # Reload nginx to ensure it's serving the latest files
            sudo systemctl reload nginx
          EOF